### ISSUE TITLE
ラズパイがモニターに映りません。

### ISSUE THREAD

**Issue by Shuma-s58** [open-rdc/turtlebot3_trouble#1]
23年11月１日
ラズパイ内のwifi設定が書き変わっていないためにturtlebot3が動かないのではないかと思い、ラズパイとモニターをつないで設定をみようと思いました。
すると、以下の写真のような画面が出てくるだけで、ラズパイが立ち上がりませんでした。
(モニターはB3の研究室の一番奥のモニターを使いました)

![モニター1拡大版](https://github.com/open-rdc/turtlebot3_trouble/assets/115678656/94117358-589d-40b7-8c25-3e152d903cde)
![モニター２拡大版](https://github.com/open-rdc/turtlebot3_trouble/assets/115678656/1d4c9b18-2ad7-4b01-89f6-d1d528698cd7)

対策としては以下のことを試しましたが、結果は同じでした。
・別のロボットをつないでみる。
・HDMIケーブルを変えてみる。

**Comment by Yusuke-Yamasaki-555** [comment]
まず、何をしようとしたらこうなった感じですか？
turtlebotが動かなくなる前にしたことを教えてほしいです。
(余裕があればで良いです)

**Comment by Yusuke-Yamasaki-555** [comment]
あと、失敗メッセージも出ているので、そこから色々調べてみるといいと思いますよ。
メッセージをコピペするだけでいい感じの情報が出てくると思います。

**Comment by Shuma-s58** [comment]
まず、turtlebot3が動いているところはまだ一度も確認できていないです。
（後期からの参入ということもあり、前期にどうなっていたかはよく分かっていないです）

turtlebot3に対して行ったことは以下の通りです。
・SDカードにラズパイ imager経由でUbuntu 20.04 Serverを書き込みました。
・パソコンでもubuntu20.04に色々とインストールしました。（しかし、一度もturtlebot3とは遠隔で繋がれていないので、関係ないと思っています。）

また、SDカードへの書き込みが影響してしまっている可能性も考えられたので、何も手を加えていないturtlebot3についてもラズパイとモニターをつないでみましたが、似たような結果となりました。
（何が書かれていたかについては、よく見ていませんでした。すみません。）

加えて、写真ではわからないのですが、1枚目の画面になった後すぐに2枚目のような表示になってしまっています。
それがループするような感じです。
（この２枚の写真は動画から抜き出して、載せています。）

エラーメッセージについては、よく調べてみようと思います。
分かりにくい部分があったら、すみません。

**Comment by Yusuke-Yamasaki-555** [comment]
ありがとうございます。
私の方でも調べてみましたが、turtlebotやモニタが壊れているわけではなく、raspi+ubuntu20.04の問題だと思われます。実際その手順を踏まれたとのことなので、コレで間違い無いと思います。
以下の2つ、解決の参考になるサイトを見つけたので、共有します。

https://pyhaya.hatenablog.com/entry/2021/07/11/180419

https://bugs.launchpad.net/ubuntu/+source/u-boot/+bug/1914878


調べ方としては、表示メッセージにFailed~っていうのが書いてあるので、その1行をそのまま調べると、良い感じの情報が出てきます。あと原因のファイルである“uboot/ubuntu/boot.sel”でも情報が出るので、そこら辺から解決策を探っていけばいいと思います。

**Comment by Shuma-s58** [comment]
ありがとうございます。
まずは、共有させていただいたものなどから解決策を探っていきたいと思います。

**Comment by Shuma-s58** [comment]
まだすべては試せてはいないのですが、現状について書いておきます。

**モニターに映らない件について**
・“uboot/ubuntu/boot.sel”が原因のファイルとなっているということだったので、SDカードの中身を書き換えてみましたが、
　結果はあまり変わりませんでした。
・まだ、ラズパイimagerを再インストールしてからの書き込みはまだ行っていないので後日試したいと思います。

**turtlebot3が動かせていない件について**
・ubuntuからのssh接続に関して、”**systemctl**”関連の問題があったことが分かりました。
　systemctl関連の問題については修正できましたが、他にも確認すべき事項があることがわかったので、
　それも後日確かめようと思います。

**Comment by Yusuke-Yamasaki-555** [comment]
SDカードの中身を書き換えた、とのことですが、具体的にはどのようなことをしましたか？
貼ったリンクに以下2つの方法が提案されていますが、それを試してみたということでしょうか。
- ddコマンドでsdにosを焼く
- Raspberry Pi Imagerのadvanced optionをリセットする。

**Comment by Shuma-s58** [comment]
SDカードの中身を変えたというのは以下の通りです。
・最初、Ubuntu 20.04 Serverが入っていたので、それをturtlebot3公式が提供しているイメージに書き換えました。
・その後、SDカードの中身を完全に消去してからturtlebot3公式が提供しているイメージを書き入れました。
（1つ目の操作を行う際に「カードの中身を消去しますか？」と出ていたのですが、それでは完全には消去できていないという旨の記事を見たので）
上記のどちらでもあまり大きな変化はなかったです。

**「ddコマンドでsdにosを焼く」**
これに関しては、そもそもどこでそのコマンドが打てるのかがわかりませんでした。
(コマンドプロンプトにて”C:\users\”から”I:”へ移動できるというのは分かったのですが、SDカードに対して何かコマンド操作ができるような感じではなかったです。これに関しては自分の使っているカードリーダが問題の可能性もあります)

**Raspberry Pi Imagerのadvanced optionをリセットする。**
これについても試してみましたが、あまり効果はなかったように思います。
もしかしたら、リンク先の記事を書いた人が意図したようにはリセット出来ていなかった可能性もあります。

Raspberry Pi Imagerのadvanced optionに関する他の記事を少し見ていたところ、imagerの再インストールでうまくいったというのを見たので、それを後日試してみようと思っています。

**Comment by Yusuke-Yamasaki-555** [comment]
なるほど。詳しくありがとうございます。

　ddコマンドに関してなのですが、コレはlinux系OSのコマンドなので、ナイティブのlinux系OSからimageを焼くときに使えます(WSLだと正常にいけるか知らないので、ネイティブ環境が1番です)。
　なので方法としては、ネイティブのlinux系OSが入っているPCにSDカードを接続して、PCからddコマンドによってSDカードにOSを焼く、という感じになります。

詳しい使い方とか方法は、「コマンド　dd liveUSB」とかで調べるといいと思います。

**Comment by yasuohayashibara** [comment]
個別に問題解決していると時間がかかりそうな気がしますので，Turtlebot3の運用経験抱負な望月君に対面で相談してみると良さそうな気がします．

あと，noeticだと少し制限事項が発生しますので，ご注意ください．
https://emanual.robotis.com/docs/en/platform/turtlebot3/quick-start/

**Comment by Shuma-s58** [comment]
@Yusuke-Yamasaki-555 
ありがとうございます。少し調べてみようと思います。
@yasuohayashibara 
分かりました。望月さんに連絡を取ってみようと思います。
（おそらく、今週はつくばチャレンジで難しいと思うので、来週までは自身で試せることは試していきたいと思います）
noeticを使うかどうかについては少し検討してみます。

**Comment by Shuma-s58** [comment]
モニターの件について
ラズパイに繋いでいたコネクタの電力不足が原因であったことが分かりました。
(2.5A必要なところに1Aのものを繋いでいました)
次回からは仕様書の内容も精読した上で対策を講じたいと思います。

**Comment by yasuohayashibara** [comment]
解決したと判断したらissueを閉じるようにしてください．
